// 首次流程使用真实时间验收，取消/重复操作用浏览器时钟加速回归。
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')

async function main() {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  try {
    fs.mkdirSync('.qa', { recursive: true })
    const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } })
    page.setDefaultTimeout(15000)
    const errors = [], external = []
    page.on('pageerror', e => errors.push(e.message))
    page.on('console', m => { if (['error', 'warning'].includes(m.type())) errors.push(m.text()) })
    page.on('request', r => { if (!r.url().startsWith('http://127.0.0.1:5173') && !r.url().startsWith('data:')) external.push(r.url()) })
    await page.goto('http://127.0.0.1:5173/#/smart-patrol')
    const heading = () => page.getByRole('heading', { name: '智慧轮巡', exact: true }).waitFor()
    await heading()
    const start = page.getByRole('button', { name: '开始智慧轮巡', exact: true })
    const review = page.getByRole('button', { name: '高码流复核', exact: true })
    const reset = page.getByRole('button', { name: '重置演示', exact: true })
    const card = id => page.locator(`[data-camera="${id}"]`)
    const bandwidth = page.getByTestId('bandwidth-total')
    const logs = page.locator('.patrol-log > div')
    const records = page.locator('.patrol-record-panel tbody tr').filter({ hasText: /EVT-/ })
    const nav = page.getByRole('navigation', { name: '系统导航' })
    const verifyIdle = async () => {
      assert.equal(await page.locator('.monitor-card[data-state="idle"]').count(), 4)
      assert.equal(await page.locator('.monitor-card.hd').count(), 0)
      assert.equal(await bandwidth.innerText(), '2.0Mbps')
      assert.equal(await logs.count(), 0)
      assert.equal(await records.count(), 0)
      assert.ok(await start.isEnabled())
      assert.ok(await review.isDisabled())
    }
    await verifyIdle()
    assert.equal(await page.locator('.patrol-model-tags span').count(), 8)
    assert.equal(await page.locator('.road-scene').count(), 4)
    assert.ok((await card('CAM001').innerText()).includes('K18'))
    assert.ok((await card('CAM003').innerText()).includes('K62'))
    await page.screenshot({ path: '.qa/patrol-idle-1920.png', fullPage: true })
    const began = Date.now()
    await start.click()
    assert.ok(await start.isDisabled())
    assert.ok(await review.isDisabled())
    for (const id of ['CAM001', 'CAM002', 'CAM003']) {
      await page.locator(`[data-camera="${id}"][data-state="analyzing"]`).waitFor()
      await page.locator(`[data-camera="${id}"][data-state="normal"]`).waitFor()
    }
    await page.locator('[data-camera="CAM004"][data-state="suspected"]').waitFor()
    const suspectedAt = Date.now()
    assert.equal(await records.count(), 0)
    assert.ok(await review.isEnabled())
    assert.equal(await bandwidth.innerText(), '2.0Mbps')
    assert.ok((await page.locator('.patrol-event').innerText()).includes('96%'))
    assert.ok((await page.locator('.patrol-event').innerText()).includes('待复核'))
    assert.ok((await card('CAM004').innerText()).includes('640×360'))
    await page.screenshot({ path: '.qa/patrol-suspected-1920.png', fullPage: true })
    const reviewBegan = Date.now()
    await review.click()
    assert.ok(await review.isDisabled())
    await page.locator('[data-camera="CAM004"][data-state="requesting"]').waitFor()
    assert.equal(await bandwidth.innerText(), '2.0Mbps')
    await page.locator('[data-camera="CAM004"].hd').waitFor()
    assert.equal(await bandwidth.innerText(), '5.5Mbps')
    assert.ok((await card('CAM004').innerText()).includes('1920×1080'))
    assert.ok((await card('CAM004').innerText()).includes('4Mbps'))
    await page.screenshot({ path: '.qa/patrol-hd-1920.png', fullPage: true })
    await page.locator('[data-camera="CAM004"][data-state="confirmed"]').waitFor()
    const automaticDuration = suspectedAt - began + Date.now() - reviewBegan
    assert.ok(automaticDuration >= 19500 && automaticDuration <= 32000, `自动流程耗时 ${automaticDuration}`)
    assert.equal(await records.count(), 1)
    assert.ok((await records.innerText()).includes('G4京港澳高速'))
    assert.ok((await records.innerText()).includes('K2035'))
    assert.ok((await page.locator('.patrol-event').innerText()).includes('99%'))
    assert.ok(await review.isDisabled())
    assert.ok(await start.isDisabled())
    assert.equal(await logs.count(), 13)
    const sharedEvent = await page.evaluate(async () => {
      // 使用应用实际加载的模块 URL，避免 Vite 的扩展名/HMR URL 生成另一实例。
      const moduleUrl = performance.getEntriesByType('resource').map(entry => entry.name).find(url => /\/src\/data\/events(?:\.js)?(?:\?|$)/.test(url))
      const { confirmedMainEvent } = await import(moduleUrl)
      return JSON.parse(JSON.stringify(confirmedMainEvent.value))
    })
    for (const [key, value] of Object.entries({ road: 'G4京港澳高速', location: 'K2035', camera: 'CAM004', eventType: '交通事故', weather: '暴雨', speed: 18, flow: 4200, queueLength: 2.3, status: '已确认' })) assert.equal(sharedEvent[key], value)
    await page.screenshot({ path: '.qa/patrol-confirmed-1920.png', fullPage: true })
    await nav.getByRole('link', { name: /堵点分析/ }).click()
    await page.getByRole('heading', { name: '堵点分析', exact: true }).waitFor()
    await nav.getByRole('link', { name: /智慧轮巡/ }).click()
    await heading()
    assert.equal(await records.count(), 1)
    assert.ok((await page.locator('.patrol-event').innerText()).includes('已确认'))
    await reset.click()
    await verifyIdle()

    // 在每一个异步阶段重置，再推进时间，确认旧回调不会恢复事件。
    await page.clock.install()
    for (const offset of [1000, 14000, 15000, 17000, 19000]) {
      await start.click()
      if (offset >= 14000) {
        await page.clock.runFor(14010)
        if (offset > 14000) { await review.click(); await page.clock.runFor(offset - 14000) }
      } else await page.clock.runFor(offset)
      await reset.click()
      await page.clock.runFor(30000)
      await verifyIdle()
    }
    // 轮巡中切走：取消当前任务；高清复核中切走：回退待复核和低码流。
    await start.click()
    await page.clock.runFor(1000)
    await nav.getByRole('link', { name: /视频编目/ }).click()
    await page.getByRole('heading', { name: '视频编目管理', exact: true }).waitFor()
    await page.clock.runFor(30000)
    await nav.getByRole('link', { name: /智慧轮巡/ }).click(); await heading(); await verifyIdle()
    await start.click(); await page.clock.runFor(14010); await review.click(); await page.clock.runFor(4010)
    await nav.getByRole('link', { name: /路网总览/ }).click()
    await page.getByRole('heading', { name: '路网运行监测总览', exact: true }).waitFor()
    await page.clock.runFor(30000)
    await nav.getByRole('link', { name: /智慧轮巡/ }).click(); await heading()
    assert.ok(await review.isEnabled()); assert.equal(await bandwidth.innerText(), '2.0Mbps'); assert.equal(await records.count(), 0)
    await review.click(); await page.clock.runFor(6010)
    assert.equal(await records.count(), 1)
    await page.evaluate(() => { document.querySelector('.review-action button').click(); document.querySelector('.patrol-actions button:last-child').click() })
    await page.clock.runFor(30000)
    assert.equal(await records.count(), 1)
    for (const viewport of [{ width: 1366, height: 768 }, { width: 390, height: 844 }]) {
      await page.setViewportSize(viewport)
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '页面横向溢出')
      await page.screenshot({ path: `.qa/patrol-${viewport.width}.png`, fullPage: true })
    }
    await page.reload(); await heading(); assert.equal(await records.count(), 1); assert.equal(await page.locator('.monitor-card[data-state="confirmed"]').count(), 1); assert.equal(await bandwidth.innerText(), '5.5Mbps')
    assert.deepEqual(errors, [])
    assert.deepEqual(external, [])
    console.log(JSON.stringify({ result: 'PASS', automaticSeconds: +(automaticDuration / 1000).toFixed(1), checks: ['四路动画', '逐路正常及事故', '低高清参数和带宽', '置信度96到99', '动态13条日志', '唯一确认记录', '共享事件数据', '5个阶段重置', '离开页面取消任务', '确认状态跨路由保留', '重复操作防护', '刷新恢复确认检查点', '响应式无横向溢出'], errors, external }, null, 2))
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exit(1) })

