// 浏览器验收：使用外部 Playwright，不增加项目依赖。
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')

async function main() {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  try {
    fs.mkdirSync('.qa', { recursive: true })
    const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } })
    const errors = []
    const external = []
    page.on('pageerror', e => errors.push(e.message))
    page.on('console', m => { if (['error', 'warning'].includes(m.type())) errors.push(m.text()) })
    page.on('request', r => { if (!r.url().startsWith('http://127.0.0.1:5173') && !r.url().startsWith('data:')) external.push(r.url()) })
    await page.goto('http://127.0.0.1:5173/#/video-catalog')
    await page.getByRole('heading', { name: '视频编目管理', exact: true }).waitFor()
    const tree = page.getByRole('navigation', { name: '视频资源目录树' })
    const table = page.locator('.catalog-table tbody')
    const query = page.locator('.catalog-query')
    const modal = () => page.getByRole('dialog')
    const reset = () => query.getByRole('button', { name: '重置', exact: true }).click()
    const search = () => query.getByRole('button', { name: '查询', exact: true }).click()
    const count = () => table.locator('tr').count()
    const stat = label => page.locator('.catalog-stats article').filter({ hasText: label }).locator('strong').innerText()
    assert.equal(await stat('视频资源总数'), '15路')
    assert.equal(await stat('在线视频'), '11路')
    assert.equal(await stat('离线视频'), '2路')
    assert.equal(await stat('已共享资源'), '13路')
    await page.screenshot({ path: '.qa/catalog-1920.png', fullPage: true })
    assert.equal(await count(), 6)
    await page.getByRole('button', { name: '下一页', exact: true }).click()
    assert.ok((await table.innerText()).includes('深圳京深线'))
    await page.getByRole('button', { name: '下一页', exact: true }).click()
    assert.equal(await count(), 3)
    await reset()
    await tree.getByRole('button', { name: /^广州市/ }).click()
    assert.equal(await count(), 4)
    await tree.getByRole('button', { name: '展开广州市', exact: true }).click()
    await tree.getByRole('button', { name: /^G4京港澳高速/ }).click()
    assert.equal(await count(), 2)
    await tree.getByRole('button', { name: '收起广州市', exact: true }).click()
    assert.equal(await tree.getByRole('button', { name: /^G4京港澳高速/ }).count(), 0)
    await reset()
    await tree.getByRole('button', { name: /^高速公路/ }).click()
    assert.equal(await count(), 5)
    await tree.getByRole('button', { name: /^应急指挥/ }).click()
    assert.equal(await count(), 2)
    await reset()
    await query.getByLabel('所属区域', { exact: true }).selectOption('广州市')
    await query.getByLabel('所属道路', { exact: true }).selectOption('G4京港澳高速')
    await query.getByLabel('在线状态', { exact: true }).selectOption('离线')
    await query.getByLabel('业务分类', { exact: true }).selectOption('高速公路')
    await search()
    assert.equal(await count(), 1)
    assert.ok((await table.innerText()).includes('K2030'))
    await reset()
    for (const keyword of ['K2035', 'GD-GZ-G4-K2035-CAM-001', 'G4京港澳高速K2035监控点']) {
      await query.getByLabel('关键词', { exact: true }).fill(keyword)
      await search()
      assert.equal(await count(), 1)
    }
    await query.getByLabel('关键词', { exact: true }).fill('不存在的资源')
    await search()
    assert.ok(await page.getByText('未找到匹配资源，请调整目录或查询条件。').isVisible())
    await reset()
    await query.getByLabel('在线状态', { exact: true }).selectOption('故障')
    await search()
    assert.equal(await count(), 2)
    assert.equal(await table.locator('.status.danger').count(), 2)
    await reset()

    async function fillNew(name, stake = 'K2035') {
      await page.getByRole('button', { name: '＋ 新增视频', exact: true }).click()
      await modal().getByLabel('城市 *', { exact: true }).selectOption('广州市')
      await modal().getByLabel('道路 *', { exact: true }).selectOption('G4京港澳高速')
      await modal().getByLabel('桩号 *', { exact: true }).fill(stake)
      await modal().getByLabel('视频名称 *', { exact: true }).fill(name)
    }
    await page.getByRole('button', { name: '＋ 新增视频', exact: true }).click()
    await modal().getByRole('button', { name: '生成编码', exact: true }).click()
    assert.ok(await modal().getByRole('alert').isVisible())
    await modal().getByRole('button', { name: '保存', exact: true }).click()
    assert.ok(await modal().isVisible())
    assert.equal(await page.locator('.catalog-form :invalid').count() > 0, true)
    await page.keyboard.press('Escape')
    assert.equal(await page.locator('dialog').count(), 0)
    await fillNew('现场演示新增资源')
    await modal().getByRole('button', { name: '保存', exact: true }).click()
    assert.ok((await modal().getByRole('alert').innerText()).includes('生成编码'))
    await modal().getByLabel('一体化平台目录', { exact: true }).selectOption('高速公路')
    await modal().getByLabel('外部共享目录', { exact: true }).selectOption('应急指挥')
    await modal().getByRole('button', { name: '生成编码', exact: true }).click()
    assert.equal(await modal().getByLabel('视频编码 *', { exact: true }).inputValue(), 'GD-GZ-G4-K2035-CAM-002')
    assert.ok((await modal().getByRole('status').innerText()).includes('生成唯一视频编码'))
    await modal().getByLabel('桩号 *', { exact: true }).fill('K2036')
    assert.equal(await modal().getByLabel('视频编码 *', { exact: true }).inputValue(), '')
    await modal().getByLabel('桩号 *', { exact: true }).fill('K2035')
    await modal().getByRole('button', { name: '生成编码', exact: true }).click()
    await page.screenshot({ path: '.qa/catalog-add-1920.png', fullPage: true })
    await modal().getByRole('button', { name: '保存', exact: true }).click()
    assert.equal(await page.locator('dialog').count(), 0)
    assert.equal(await stat('视频资源总数'), '16路')
    assert.equal(await stat('在线视频'), '12路')
    assert.equal(await stat('已共享资源'), '14路')
    assert.ok((await table.locator('tr').first().innerText()).includes('现场演示新增资源'))
    await tree.getByRole('button', { name: /^应急指挥/ }).click()
    assert.equal(await count(), 3)
    await tree.getByRole('button', { name: /^高速公路/ }).click()
    assert.equal(await count(), 6)
    await reset()
    await table.locator('tr').first().getByRole('button', { name: '查看', exact: true }).click()
    for (const title of ['基础信息', '编目信息', '共享信息', '运行状态', '编码规则（创建时快照）']) assert.ok(await modal().getByRole('heading', { name: title, exact: true }).isVisible())
    assert.ok((await modal().innerText()).includes('GD-GZ-G4-K2035-CAM-002'))
    await page.screenshot({ path: '.qa/catalog-details.png', fullPage: true })
    await modal().getByRole('button', { name: '关闭弹窗' }).click()
    await table.locator('tr').first().getByRole('button', { name: '编辑', exact: true }).click()
    await modal().getByLabel('视频名称 *', { exact: true }).fill('编辑后的共享资源')
    await modal().getByLabel('设备类型 *', { exact: true }).selectOption('球型摄像机')
    await modal().getByLabel('业务分类 *', { exact: true }).selectOption('桥梁')
    await modal().getByLabel('一体化平台目录', { exact: true }).selectOption('桥梁')
    await modal().getByLabel('外部共享目录', { exact: true }).selectOption('')
    await modal().getByRole('button', { name: '保存', exact: true }).click()
    assert.equal(await stat('视频资源总数'), '16路')
    assert.ok((await table.locator('tr').first().innerText()).includes('球型摄像机'))
    await tree.getByRole('button', { name: /^桥梁/ }).click()
    assert.equal(await count(), 2)
    await tree.getByRole('button', { name: /^应急指挥/ }).click()
    assert.equal(await count(), 2)
    await reset()
    await fillNew('第二个新增资源')
    await modal().getByRole('button', { name: '生成编码', exact: true }).click()
    assert.equal(await modal().getByLabel('视频编码 *', { exact: true }).inputValue(), 'GD-GZ-G4-K2035-CAM-003')
    await modal().getByRole('button', { name: '保存', exact: true }).click()
    assert.equal(await stat('视频资源总数'), '17路')
    assert.equal(await stat('已共享资源'), '14路')

    await page.getByRole('button', { name: '编码规则', exact: true }).click()
    await modal().getByRole('button', { name: /普通公路/ }).click()
    await modal().getByLabel('领域标识', { exact: true }).fill('RD2')
    await modal().getByLabel('序号位数', { exact: true }).selectOption('4')
    await modal().getByRole('button', { name: '应用规则', exact: true }).click()
    assert.ok((await modal().getByRole('status').innerText()).includes('规则已应用'))
    await page.screenshot({ path: '.qa/catalog-rules.png', fullPage: true })
    await modal().getByLabel('领域标识', { exact: true }).fill('FAC')
    await modal().getByRole('button', { name: '应用规则', exact: true }).click()
    assert.ok((await modal().getByRole('alert').innerText()).includes('其他领域'))
    await modal().getByRole('button', { name: '关闭弹窗' }).click()
    await fillNew('普通公路新增资源')
    await modal().getByLabel('领域 *', { exact: true }).selectOption('ordinary')
    assert.equal(await modal().getByLabel('道路 *', { exact: true }).inputValue(), '')
    await modal().getByLabel('道路 *', { exact: true }).selectOption('G105京澳线')
    await modal().getByLabel('业务分类 *', { exact: true }).selectOption('普通公路')
    await modal().getByRole('button', { name: '生成编码', exact: true }).click()
    assert.equal(await modal().getByLabel('视频编码 *', { exact: true }).inputValue(), 'GD-GZ-RD2-G105-K2035-CAM-0001')
    await modal().getByRole('button', { name: '保存', exact: true }).click()
    const nav = page.getByRole('navigation', { name: '系统导航' })
    await nav.getByRole('link', { name: /智慧轮巡/ }).click()
    await page.getByRole('heading', { name: '智慧轮巡', exact: true }).waitFor()
    assert.equal(await page.locator('.video-placeholder').count(), 4)
    await nav.getByRole('link', { name: /视频编目/ }).click()
    await page.getByRole('heading', { name: '视频编目管理', exact: true }).waitFor()
    assert.equal(await stat('视频资源总数'), '18路')
    await page.reload()
    await page.getByRole('heading', { name: '视频编目管理', exact: true }).waitFor()
    assert.equal(await stat('视频资源总数'), '15路')

    for (const viewport of [{ width: 1366, height: 768 }, { width: 390, height: 844 }]) {
      await page.setViewportSize(viewport)
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '页面横向溢出')
      await fillNew('尺寸测试')
      const bounds = await modal().boundingBox()
      assert.ok(bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= viewport.width && bounds.y + bounds.height <= viewport.height, '弹窗超出屏幕')
      await modal().getByRole('button', { name: '生成编码', exact: true }).click()
      await modal().getByRole('button', { name: '保存', exact: true }).scrollIntoViewIfNeeded()
      await page.screenshot({ path: `.qa/catalog-modal-${viewport.width}.png`, fullPage: false })
      await modal().getByRole('button', { name: '取消', exact: true }).click()
    }
    assert.deepEqual(errors, [])
    assert.deepEqual(external, [])
    console.log(JSON.stringify({ result: 'PASS', checks: ['15条样例及统计', '目录展开收起和三级筛选', '独立共享目录', '复合查询与空状态', '分页重置', '必填校验', '002与003唯一编码', '输入改变废弃旧编码', '新增和编辑保存', '详情规则快照', '规则配置与领域联动', '跨路由保留和刷新复位', '轮巡仍为四路', '弹窗响应式'], browserErrors: errors, externalRequests: external }, null, 2))
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exit(1) })
